### ISSUE TITLE
Add option to export without backdrop

### ISSUE THREAD

**Issue by lunelson** [octref/polacode#22]
Although it's clear that part of the point here is to have the shadows, i think the nicely rounded corners are still compelling without, and it would be nice to have the option to turn them off. Also, because they are currently being cut off anyway, at least in my test—so another option would be to expand the edges so the shadow is contained. Basically, the same choice as we have on macOS, to screenshot a window with or without the option key.

Thanks for this great addition to vscode!

![code](https://user-images.githubusercontent.com/1242864/36340034-0393d9fa-13d3-11e8-81df-00471d6c9f6c.png)

**Comment by timpulver** [comment]
Would be great to have two modes:

- **With shadow**: draws a shadow (party transparent) around the code-area, because of drawing the shadow with transparency the image will look good on every background where it is displayed
- **Without shadow**: Sides are cropped (code area maximized), transparent background, so the corners are left out and the image works on every background

The version right now won’t look good in many places because of the opaque background

**Comment by octref** [comment]
No backdrop or transparent backdrop looks pretty ugly to me.

GitHub

![code](https://user-images.githubusercontent.com/4033249/36350089-2ed37c7e-1446-11e8-995d-41f50a6625f7.png)
![code](https://user-images.githubusercontent.com/4033249/36350097-50665672-1446-11e8-8de9-d766b363535b.png)

Twitter

![image](https://user-images.githubusercontent.com/4033249/36350105-8902aabc-1446-11e8-8149-40e55ec2c907.png)
![image](https://user-images.githubusercontent.com/4033249/36350111-9e85a132-1446-11e8-8358-26e66832ae74.png)

Provide example where they might be looking good.

**Comment by lunelson** [comment]
The point of having a transparent background is to be able to place it over any underlying color or graphics; obviously, over black or very dark colors—the idea here is basically to have similar kinds of options as one has with carbon.now.sh: you can get a transparent background by selecting the "image" option but uploading no image. 

The following were made on macOS

![artboard copy 2](https://user-images.githubusercontent.com/1242864/36350216-f79962ba-1494-11e8-8bfb-80b95cccafed.png)
![artboard copy 3](https://user-images.githubusercontent.com/1242864/36350217-f7b32a1a-1494-11e8-9ae0-57a1e122eb20.png)
![artboard copy](https://user-images.githubusercontent.com/1242864/36350218-f7cbdc2c-1494-11e8-88ad-3ef5792f0a32.png)
![artboard](https://user-images.githubusercontent.com/1242864/36350219-f7e510f2-1494-11e8-9b7e-e18bb48a6757.png)

**Comment by timpulver** [comment]
In context having a cropped screenshot will often look better because the edges of the code area are aligned with the surrounding content.

![without_sha_zeichenflache 1](https://user-images.githubusercontent.com/1055819/36351141-74aff5c4-14a5-11e8-9d2c-4ea5034d0851.png)

![withsha_zeichenflache 1](https://user-images.githubusercontent.com/1055819/36351145-797a5e46-14a5-11e8-8524-b4c3b0bc91c3.png)

**Comment by StanleySathler** [comment]
@octref where are you planning to add this option? Maybe a checkbox/custom toggle component just above the "export" button?

**Comment by pmolaro** [comment]
PLUS 1 for this feature

**Comment by gugadev** [comment]
I think the best way is to export to a transparent image with shadow, just like mac does.

![](https://i.imgur.com/1Hf9KzT.png)

**Comment by johnpapa** [comment]
One use case for no backdrop or transparent bground is for slides (powerpoint, keynote, google slides, etc)

**Comment by tobi-or-not-tobi** [comment]
@johnpapa I've done a small local fix to have transparent background, no backdrop or basically any change you like to make for the exact same reason as you bring up. See https://github.com/octref/polacode/issues/55#issuecomment-397989942.
