### ISSUE TITLE
Normalize indentation

### ISSUE THREAD

**Issue by jgierer12** [octref/polacode#6]
When pasting an indented code snippet, Polacode will keep its indentation. This leads to weird looking images such as this:
![shot](https://user-images.githubusercontent.com/4331946/36300030-d8aa8d3e-12ff-11e8-88cd-3a334612cbd1.png)
It would be great if Polacode would normalize the indentation on paste, similar to VS Code's native *Format on Save* feature.

**Comment by octref** [comment]
I don't think formatting would be nice, because it complicates the logic and I don't want to take blame for formatter's fault.

Something I will have is having an option to remove initial indentation. Polacode would look through all lines, find the one with shortest indentation (let's say 4 spaces) and remove 4 spaces from all lines.

**Comment by jgierer12** [comment]
> Something I will have is having an option to remove initial indentation

Yes, that's exactly what I had in mind. I agree that a full formatter may be needlessly complicated.
